---

# tasks file for Amlen

- name: Set OpenShift Objects to {{ _amlen_state }}
  k8s:
    state: "{{ _amlen_state }}"
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
  - ./templates/service_account.j2
  - ./templates/service.j2

- name: create HA pairs
  include_tasks: create_pair.yml
  loop: "{{ range(0,size,1)|list}}"
  loop_control:
    loop_var: pair_id
