# permissions for end users to view amlens.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: amlen-viewer-role
rules:
- apiGroups:
  - amlen.com
  resources:
  - amlens
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - amlen.com
  resources:
  - amlens/status
  verbs:
  - get
