kind: ConfigMap
apiVersion: v1
metadata:
  name: amlen-config
immutable: True
data:
  config: '{
    "MessageHub": {
      "IoTMessageHub": {
        "Description": "Amlen Message Hub"
      }
    },
    "ConnectionPolicy": {
      "IoTConnectionPolicy": {
        "Protocol": "MQTT",
        "AllowDurable": true,
        "AllowPersistentMessages": true,
        "Description": "IoT Connection Policy",
        "MaxSessionExpiryInterval": 3888000
      }
    },
    "TopicPolicy": {
      "IoTMessagingPolicy": {
        "Topic": "*",
        "ActionList": "Publish,Subscribe",
        "Protocol": "MQTT",
        "MaxMessages": 5000,
        "MaxMessagesBehavior": "DiscardOldMessages",
        "MaxMessageTimeToLive": "unlimited"
      }
    },
    "SubscriptionPolicy": {
      "IoTSubscriptionPolicy": {
        "Subscription": "*",
        "ActionList": "Receive,Control",
        "Protocol": "MQTT",
        "MaxMessages": 100000,
        "MaxMessagesBehavior": "DiscardOldMessages"
      }
    },
    "TrustedCertificate": [
      {
        "TrustedCertificate": "ca.crt",
        "SecurityProfileName": "IoTSecurityProfile",
        "Overwrite": true
      }
    ],
    "CertificateProfile": {
      "IoTCertificate": {
        "Certificate": "tls.crt",
        "Key": "tls.key",
        "Overwrite": true
      }
    },
    "SecurityProfile": {
      "IoTSecurityProfile": {
        "MinimumProtocolMethod": "TLSv1.2",
        "UseClientCertificate": true,
        "Ciphers": "Fast",
        "CertificateProfile": "IoTCertificate",
        "UseClientCipher": false,
        "UsePasswordAuthentication": false,
        "TLSEnabled": true
      }
    },
    "Endpoint": {
      "IoTSecureEndpoint0": {
        "Enabled": true,
        "Port": 8883,
        "Protocol": "MQTT",
        "SecurityProfile": "IoTSecurityProfile",
        "MessageHub": "IoTMessageHub",
        "Interface": "all",
        "MaxMessageSize": "1024KB",
        "ConnectionPolicies": "IoTConnectionPolicy",
        "TopicPolicies": "IoTMessagingPolicy",
        "SubscriptionPolicies": "IoTSubscriptionPolicy"
      }
    },
    "TraceBackupCount": 100
  }'
