// By default we build on the oldest supported distro (centos7)
// A Jenkinsfile used for other distros (with associated build container Dockerfiles)
// along with other jenkins files we use are all in server_build/buildcontainer
//

pipeline {
  agent any
  stages {
        stage('Create Amlen Image') {
            steps {
                script {
                    if (env.BUILD_LABEL == null ) {
                        env.BUILD_LABEL = sh(script: "date +%Y%m%d-%H%M", returnStdout: true).toString().trim() +"_eclipsecentos7"
                    }
                }
                echo "In Init, BUILD_LABEL is ${env.BUILD_LABEL}"    
                sh 'pwd && cd operator/build && docker build -t quay.io/ianboden/amlen:v1.0.31 . && docker push quay.io/ianboden/amlen:v1.0.31'
            }
        }
        stage('Create Operator Image') {
            steps {
                script {
                    if (env.BUILD_LABEL == null ) {
                        env.BUILD_LABEL = sh(script: "date +%Y%m%d-%H%M", returnStdout: true).toString().trim() +"_eclipsecentos7"
                    }
                }
                echo "In Init, BUILD_LABEL is ${env.BUILD_LABEL}"    
                sh 'pwd && free -m && cd operator && docker build -t quay.io/ianboden/amlen-operator:v1.0.378. && docker push quay.io/ianboden/amlen-operaotr:v1.0.378'
            }
        }
    }
    post {
        // send a mail on unsuccessful and fixed builds
        unsuccessful { // means unstable || failure || aborted
            emailext subject: 'Build $BUILD_STATUS $PROJECT_NAME #$BUILD_NUMBER!', 
            body: '''Check console output at $BUILD_URL to view the results.''',
            recipientProviders: [culprits(), requestor()], 
            to: 'ianboden@uk.ibm.com'
        }
        fixed { // back to normal
            emailext subject: 'Build $BUILD_STATUS $PROJECT_NAME #$BUILD_NUMBER!', 
            body: '''Check console output at $BUILD_URL to view the results.''',
            recipientProviders: [culprits(), requestor()], 
            to: 'ianboden@uk.ibm.com'
        }
    }
}
